name: CI
on:
  pull_request:
  merge_group:
  push:
    branches: [main]

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ossystems/nix-actions@v1
        with:
          install-nix: true   # public flake, no token needed
